name: "Build Debian Live Minimal ISO"

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Get Date"
        run: |
          echo "DATESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV 

      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: "Build Image"
        run: |
          ./build.sh
      
      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "Armbian Installer x86_64 ISO"
          body_path: ${{ github.workspace }}/info.md
          files: |
            output/armbian-installer-x86_64.iso
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
